# Generated by Django 6.0.6 on 2026-06-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('motor_jogos', models.CharField(max_length=128)),
                ('ano_fundada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=32)),
                ('nome', models.CharField(max_length=128)),
                ('ano_lancamento', models.DateField()),
                ('geracao', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('genero', models.CharField(max_length=128)),
                ('lancamento', models.DateField()),
                ('desenvolvedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.desenvolvedor')),
                ('plataforma', models.ManyToManyField(to='catalogo.plataforma')),
            ],
        ),
    ]
