# Generated by Django 6.0.6 on 2026-06-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='ano_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
