# Generated by Django 6.0.6 on 2026-06-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_plataforma_ano_lancamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desenvolvedor',
            name='ano_fundada',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='lancamento',
        ),
        migrations.AddField(
            model_name='desenvolvedor',
            name='ano_fundacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='ano_lancamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='ano_lancamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
